#!/run/current-system/sw/bin/bash
# Function to make commands less annoying
hc() {
  herbstclient "$@"
}

TERMINAL=kitty

# remove all existing keybindings
hc keyunbind --all

# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod4

# basic action
hc keybind $Mod-Shift-q close
hc keybind $Mod-Shift-r reload

hc keybind $Mod-Return spawn "${TERMINAL:-kitty}"

# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# focus
hc keybind $Mod-c cycle
hc keybind $Mod-Shift-c cycle -1
hc keybind $Mod-i jumpto urgent

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# frame invisibility toggle
hc keybind $Mod-v set frame_bg_transparent toggle

# tags
tag_names=( "I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X")
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
  hc add "${tag_names[$i]}"
  key="${tag_keys[$i]}"
  if ! [ -z "$key" ] ; then
    hc keybind "$Mod-Alt-$key" use_index "$i"
    hc keybind "$Mod-Alt-Shift-$key" move_index "$i"
  fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-s set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-p pseudotile toggle

# restore all minimized windows of the focused tag
hc keybind $Mod-Ctrl-m foreach CLIENT clients. \
  sprintf MINATT "%c.minimized" CLIENT \
  sprintf TAGATT "%c.tag" CLIENT and \
  , compare MINATT "=" "true" \
  , substitute FOCUS "tags.focus.name" compare TAGATT "=" FOCUS \
  , set_attr MINATT false

# The following cycles through the available layouts within a frame
hc keybind $Mod-space                                                           \
  or , and . compare tags.focus.curframe_wcount = 2                   \
  . cycle_layout +1 vertical horizontal max vertical grid    \
  , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# Apps
hc keybind $Mod-d spawn ~/.dotfiles/config/polybar/scripts/launcher.sh
hc keybind $Mod-Ctrl-Print spawn flameshot gui
