#!/run/current-system/sw/bin/bash

nitrogen --restore &
# dunst &

~/.dotfiles/config/herbstluftwm/configs/theme
~/.dotfiles/config/herbstluftwm/configs/keybinds
~/.dotfiles/config/herbstluftwm/configs/setup

# Polybar
polybar -q main -c "~/.dotfiles/config/polybar/config.ini"

