#!/run/current-system/sw/bin/bash

# wallpaper
nitrogen --set-scaled --random ~/wallpapers/catppuccin &

~/.dotfiles/config/herbstluftwm/configs/theme
~/.dotfiles/config/herbstluftwm/configs/keybinds
~/.dotfiles/config/herbstluftwm/configs/setup

# ===============Polybar==========================================
kill -9 $(pgrep -f 'polybar') >/dev/null 2>&1

polybar-msg cmd quit >/dev/null 2>&1

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

echo "Launching polybar"

polybar -c ~/.dotfiles/config/polybar/polybar.ini main 


# ==============Conky=============================================
# conky -c ~/.dotfiles/config/conky/catppuccin.conkyrc

